// The licence agreement of LX Music+ (the same file in the desktop and the mobile app): the one of LX Music
// (lyswhut), for LX Music+ and its sources (none built in), in the language of the app

/** a part of a paragraph: text, bold text, a link (the licence of the app, its repository) */
export type PactPart = string | { bold: string } | { link: 'license' | 'repo', text: string }
export interface PactParagraph {
  heading?: boolean
  parts: PactPart[]
}
export interface PactText {
  title: string
  /** before it is accepted */
  mustAgree: string
  paragraphs: PactParagraph[]
  /** under it, before it is accepted */
  acceptTip: string
}

export interface PactApp {
  /** desktop / mobile */
  platform: 'desktop' | 'mobile'
  /** the licence of the app: AGPL (desktop), Apache (mobile) */
  license: 'agpl' | 'apache'
}

type Lang = 'en' | 'cn' | 'tw' | 'ja' | 'ko' | 'es' | 'pt' | 'ru' | 'vi' | 'de' | 'fr' | 'it' | 'pl'
const OTHER_LANGS: Lang[] = ['ja', 'ko', 'es', 'pt', 'ru', 'vi', 'de', 'fr', 'it', 'pl']
const getLang = (locale: string): Lang => {
  const value = locale.toLowerCase().replace('_', '-')
  if (/^zh-(tw|hk|hant)/.test(value)) return 'tw'
  if (value.startsWith('zh')) return 'cn'
  return OTHER_LANGS.find(lang => value.startsWith(lang)) ?? 'en'
}

const AGPL = 'GNU AGPL v3.0'
const LICENSE_NAMES: Record<PactApp['license'], Record<Lang, string>> = {
  agpl: {
    en: 'GNU Affero General Public License v3.0 with additional terms (no commercial use)',
    cn: 'GNU AGPL v3.0（附加禁止商业使用的条款）',
    tw: 'GNU AGPL v3.0（附加禁止商業使用的條款）',
    ja: `${AGPL}（商用利用を禁じる追加条項付き）`,
    ko: `${AGPL}(상업적 이용을 금지하는 추가 조항 포함)`,
    es: `${AGPL} con términos adicionales (sin uso comercial)`,
    pt: `${AGPL} com termos adicionais (sem uso comercial)`,
    ru: `${AGPL} с дополнительными условиями (без коммерческого использования)`,
    vi: `${AGPL} kèm điều khoản bổ sung (không dùng cho mục đích thương mại)`,
    de: `${AGPL} mit zusätzlichen Bedingungen (keine kommerzielle Nutzung)`,
    fr: `${AGPL} avec des conditions supplémentaires (pas d'usage commercial)`,
    it: `${AGPL} con termini aggiuntivi (nessun uso commerciale)`,
    pl: `${AGPL} z dodatkowymi warunkami (bez użytku komercyjnego)`,
  },
  // the same name in every language
  apache: Object.fromEntries((['en', 'cn', 'tw', ...OTHER_LANGS] as Lang[]).map(lang => [lang, 'Apache License 2.0'])) as Record<Lang, string>,
}
const PLATFORM_NAMES: Record<PactApp['platform'], Record<Lang, string>> = {
  desktop: {
    en: 'desktop',
    cn: '桌面版',
    tw: '桌面版',
    ja: 'デスクトップ版',
    ko: '데스크톱',
    es: 'de escritorio',
    pt: 'para computador',
    ru: 'для компьютера',
    vi: 'máy tính',
    de: 'Desktop',
    fr: 'pour ordinateur',
    it: 'desktop',
    pl: 'na komputer',
  },
  mobile: {
    en: 'mobile',
    cn: '移动版',
    tw: '行動版',
    ja: 'モバイル版',
    ko: '모바일',
    es: 'móvil',
    pt: 'para celular',
    ru: 'для телефона',
    vi: 'di động',
    de: 'Mobil',
    fr: 'mobile',
    it: 'mobile',
    pl: 'mobilny',
  },
}

const h = (text: string): PactParagraph => ({ heading: true, parts: [text] })
const p = (...parts: PactPart[]): PactParagraph => ({ parts })

const TEXTS: Record<Lang, (license: string, platform: string) => PactText> = {
  en: (license, platform) => ({
    title: 'License Agreement',
    mustAgree: 'You (the user) need to accept this agreement before using this software.',
    paragraphs: [
      p('This project is released under the ', { link: 'license', text: license }, '. The following agreement supplements it; where they conflict, the following agreement prevails.'),
      p('Definitions: in this agreement, "this project" means the LX Music+ ', platform, ' project, an unofficial fork of LX Music; "the user" means the person who accepts this agreement; "official music platforms" means the official platforms whose data this project shows; "copyrighted data" means data whose copyright belongs to others, including but not limited to images, audio and names.'),
      h('1. Data sources'),
      p('1.1 The online data of the official platforms is fetched from their public servers (the same data their apps show without logging in), then filtered and combined for display. This project is not responsible for the legality or accuracy of that data.'),
      p('1.2 This project cannot get audio on its own and has no built-in source. The online audio it uses comes from the links returned by the sources the user adds in Settings → Sources (Music APIs and source addons). To play a song, this project only passes the song name, artist and similar information to a source; if the source returns a link, this project uses it as the audio of the song. It cannot check whether that audio is correct, so the audio played may not match the song, or may not play. Third-party sources are made and hosted by their authors; this project is not responsible for them.'),
      p('1.3 The data that is not from official platforms (for example the lists in "My Lists") comes from the user\'s own system or the sync services the user connects to. This project is not responsible for its legality or accuracy.'),
      h('2. Copyrighted data'),
      p('2.1 Copyrighted data may be produced while using this project. This project does not own it. To avoid infringement, the user must delete the copyrighted data produced while using this project ', { bold: 'within 24 hours' }, '.'),
      h('3. Aliases of music platforms'),
      p('3.1 The aliases of the official music platforms in this project are only names used within the project and mean no harm. If an official music platform finds them inappropriate, it can contact this project to change or remove them.'),
      h('4. Use of resources'),
      p('4.1 Some resources used in this project, including but not limited to fonts and images, come from the internet. If anything infringes your rights, contact this project to have it removed.'),
      h('5. Disclaimer'),
      p('5.1 The user is responsible for any direct, indirect, special, incidental or consequential damages of any kind arising from this agreement or from the use of or inability to use this project (including but not limited to loss of goodwill, work stoppage, computer failure or malfunction, or any and all other commercial damages or losses).'),
      h('6. Restrictions'),
      p('6.1 This project is completely free and published as open source on ', { link: 'repo', text: 'GitHub' }, ' for people around the world to learn and exchange about technology. This project makes no guarantee that its technology complies with local laws and regulations.'),
      p('6.2 ', { bold: 'Do not use this project where it violates local laws and regulations.' }, ' The user bears any violation caused by using this project where local laws and regulations do not allow it, whether the user knew it or not; this project bears no direct, indirect, special, incidental or consequential liability for it.'),
      h('7. Copyright'),
      p('7.1 Running a music platform is not easy. Please respect copyright and support the official platforms.'),
      h('8. Non-commercial'),
      p('8.1 This project is only for exploring and researching technical feasibility. It accepts no commercial cooperation (including but not limited to advertising) and no donations.'),
      h('9. Acceptance'),
      p('9.1 Using this project means you accept this agreement.'),
      p('* This agreement may be updated without notice; the current version is in the open-source repository.'),
    ],
    acceptTip: 'If you (the user) accept the agreement above, press "Accept". If not, press "Decline" to quit, and delete all the data of this software.',
  }),
  cn: (license, platform) => ({
    title: '许可协议',
    mustAgree: '在使用本软件前，你（使用者）需签署本协议才可继续使用！',
    paragraphs: [
      p('本项目基于 ', { link: 'license', text: license }, ' 许可证发行。以下协议是对于该许可证的补充，如有冲突，以以下协议为准。'),
      p('词语约定：本协议中的“本项目”指 LX Music+ ', platform, '项目（LX Music 的非官方衍生版本）；“使用者”指签署本协议的使用者；“官方音乐平台”指本项目所展示数据的各官方音乐平台的统称；“版权数据”指包括但不限于图像、音频、名字等在内的他人拥有所属版权的数据。'),
      h('一、数据来源'),
      p('1.1 本项目的各官方平台在线数据来源原理是从其公开服务器中拉取数据（与未登录状态在官方平台 APP 获取的数据相同），经过对数据简单地筛选与合并后进行展示，因此本项目不对数据的合法性、准确性负责。'),
      p('1.2 本项目本身没有获取某个音频数据的能力，也不内置任何音源。本项目使用的在线音频数据来自使用者在“设置 → 音源”中自行添加的音源（音乐 API、音源插件）返回的在线链接。例如播放某首歌，本项目所做的只是将希望播放的歌曲名、艺术家等信息传递给音源，若音源返回了一个链接，则本项目将认为这就是该歌曲的音频数据而进行使用，至于这是不是正确的音频数据本项目无法校验其准确性，所以使用本项目的过程中可能会出现希望播放的音频与实际播放的音频不对应或者无法播放的问题。第三方音源由其作者制作和托管，本项目不对其负责。'),
      p('1.3 本项目的非官方平台数据（例如“我的列表”内列表）来自使用者本地系统或者使用者连接的同步服务，本项目不对这些数据的合法性、准确性负责。'),
      h('二、版权数据'),
      p('2.1 使用本项目的过程中可能会产生版权数据。对于这些版权数据，本项目不拥有它们的所有权。为了避免侵权，使用者务必在 ', { bold: '24 小时内' }, ' 清除使用本项目的过程中所产生的版权数据。'),
      h('三、音乐平台别名'),
      p('3.1 本项目内的官方音乐平台别名为本项目内对官方音乐平台的一个称呼，不包含恶意。如果官方音乐平台觉得不妥，可联系本项目更改或移除。'),
      h('四、资源使用'),
      p('4.1 本项目内使用的部分包括但不限于字体、图片等资源来源于互联网。如果出现侵权可联系本项目移除。'),
      h('五、免责声明'),
      p('5.1 由于使用本项目产生的包括由于本协议或由于使用或无法使用本项目而引起的任何性质的任何直接、间接、特殊、偶然或结果性损害（包括但不限于因商誉损失、停工、计算机故障或故障引起的损害赔偿，或任何及所有其他商业损害或损失）由使用者负责。'),
      h('六、使用限制'),
      p('6.1 本项目完全免费，且开源发布于 ', { link: 'repo', text: 'GitHub' }, ' 面向全世界人用作对技术的学习交流，本项目不对项目内的技术可能存在违反当地法律法规的行为作保证。'),
      p('6.2 ', { bold: '禁止在违反当地法律法规的情况下使用本项目。' }, '对于使用者在明知或不知当地法律法规不允许的情况下使用本项目所造成的任何违法违规行为由使用者承担，本项目不承担由此造成的任何直接、间接、特殊、偶然或结果性责任。'),
      h('七、版权保护'),
      p('7.1 音乐平台不易，请尊重版权，支持正版。'),
      h('八、非商业性质'),
      p('8.1 本项目仅用于对技术可行性的探索及研究，不接受任何商业（包括但不限于广告等）合作及捐赠。'),
      h('九、接受协议'),
      p('9.1 若你使用了本项目，即代表你接受本协议。'),
      p('* 若协议更新，恕不另行通知，可到开源地址查看。'),
    ],
    acceptTip: '若你（使用者）接受以上协议，请点击下面的“接受”按钮签署本协议；若不接受，请点击“不接受”后退出软件并清除本软件的所有数据。',
  }),
  tw: (license, platform) => ({
    title: '許可協議',
    mustAgree: '在使用本軟體前，你（使用者）需簽署本協議才可繼續使用！',
    paragraphs: [
      p('本專案基於 ', { link: 'license', text: license }, ' 授權條款發行。以下協議是對於該授權條款的補充，如有衝突，以以下協議為準。'),
      p('詞語約定：本協議中的「本專案」指 LX Music+ ', platform, '專案（LX Music 的非官方衍生版本）；「使用者」指簽署本協議的使用者；「官方音樂平台」指本專案所展示資料的各官方音樂平台的統稱；「版權資料」指包括但不限於圖像、音訊、名字等在內的他人擁有所屬版權的資料。'),
      h('一、資料來源'),
      p('1.1 本專案的各官方平台線上資料來源原理是從其公開伺服器中拉取資料（與未登入狀態在官方平台 APP 取得的資料相同），經過對資料簡單地篩選與合併後進行展示，因此本專案不對資料的合法性、準確性負責。'),
      p('1.2 本專案本身沒有取得某個音訊資料的能力，也不內建任何音源。本專案使用的線上音訊資料來自使用者在「設定 → 音源」中自行新增的音源（音樂 API、音源外掛）回傳的線上連結。例如播放某首歌，本專案所做的只是將希望播放的歌曲名、藝術家等資訊傳遞給音源，若音源回傳了一個連結，則本專案將認為這就是該歌曲的音訊資料而進行使用，至於這是不是正確的音訊資料本專案無法校驗其準確性，所以使用本專案的過程中可能會出現希望播放的音訊與實際播放的音訊不對應或者無法播放的問題。第三方音源由其作者製作和託管，本專案不對其負責。'),
      p('1.3 本專案的非官方平台資料（例如「我的列表」內列表）來自使用者本機系統或者使用者連接的同步服務，本專案不對這些資料的合法性、準確性負責。'),
      h('二、版權資料'),
      p('2.1 使用本專案的過程中可能會產生版權資料。對於這些版權資料，本專案不擁有它們的所有權。為了避免侵權，使用者務必在 ', { bold: '24 小時內' }, ' 清除使用本專案的過程中所產生的版權資料。'),
      h('三、音樂平台別名'),
      p('3.1 本專案內的官方音樂平台別名為本專案內對官方音樂平台的一個稱呼，不包含惡意。如果官方音樂平台覺得不妥，可聯絡本專案更改或移除。'),
      h('四、資源使用'),
      p('4.1 本專案內使用的部分包括但不限於字型、圖片等資源來源於網路。如果出現侵權可聯絡本專案移除。'),
      h('五、免責聲明'),
      p('5.1 由於使用本專案產生的包括由於本協議或由於使用或無法使用本專案而引起的任何性質的任何直接、間接、特殊、偶然或結果性損害（包括但不限於因商譽損失、停工、電腦故障或故障引起的損害賠償，或任何及所有其他商業損害或損失）由使用者負責。'),
      h('六、使用限制'),
      p('6.1 本專案完全免費，且開源發布於 ', { link: 'repo', text: 'GitHub' }, ' 面向全世界人用作對技術的學習交流，本專案不對專案內的技術可能存在違反當地法律法規的行為作保證。'),
      p('6.2 ', { bold: '禁止在違反當地法律法規的情況下使用本專案。' }, '對於使用者在明知或不知當地法律法規不允許的情況下使用本專案所造成的任何違法違規行為由使用者承擔，本專案不承擔由此造成的任何直接、間接、特殊、偶然或結果性責任。'),
      h('七、版權保護'),
      p('7.1 音樂平台不易，請尊重版權，支持正版。'),
      h('八、非商業性質'),
      p('8.1 本專案僅用於對技術可行性的探索及研究，不接受任何商業（包括但不限於廣告等）合作及捐贈。'),
      h('九、接受協議'),
      p('9.1 若你使用了本專案，即代表你接受本協議。'),
      p('* 若協議更新，恕不另行通知，可到開源位址查看。'),
    ],
    acceptTip: '若你（使用者）接受以上協議，請點擊下面的「接受」按鈕簽署本協議；若不接受，請點擊「不接受」後退出軟體並清除本軟體的所有資料。',
  }),
  ja: (license, platform) => ({
    title: 'ライセンス契約',
    mustAgree: 'このソフトウェアを使う前に、あなた（ユーザー）はこの契約に同意する必要があります。',
    paragraphs: [
      p('このプロジェクトは ', { link: 'license', text: license }, ' のもとで公開されています。以下の契約はそれを補足するもので、両者が食い違う場合は以下の契約が優先されます。'),
      p('用語の定義：この契約で「本プロジェクト」とは LX Music+ ', platform, ' プロジェクト（LX Music の非公式フォーク）を、「ユーザー」とはこの契約に同意した人を、「公式音楽プラットフォーム」とは本プロジェクトが表示するデータの各公式プラットフォームを、「著作権データ」とは画像・音声・名前などを含むがこれに限らない、他者が著作権を持つデータを指します。'),
      h('1. データの出どころ'),
      p('1.1 公式プラットフォームのオンラインデータは、その公開サーバーから取得したもの（ログインせずに公式アプリで見られるものと同じデータ）を、簡単に絞り込み・統合して表示しています。本プロジェクトはそのデータの合法性や正確性に責任を負いません。'),
      p('1.2 本プロジェクトは自ら音声を取得する機能を持たず、ソースも内蔵していません。本プロジェクトが使うオンライン音声は、ユーザーが「設定 → ソース」で自分で追加したソース（音楽API、ソースアドオン）が返すリンクから来ています。曲を再生するとき、本プロジェクトは曲名やアーティストなどの情報をソースに渡すだけで、ソースがリンクを返せばそれをその曲の音声として使います。その音声が正しいかどうかは確認できないため、再生される音声が曲と一致しない、または再生できないことがあります。サードパーティのソースは各作者が作成・公開しているもので、本プロジェクトはそれらに責任を負いません。'),
      p('1.3 公式プラットフォーム以外のデータ（「ライブラリ」のリストなど）は、ユーザーのシステムやユーザーが接続した同期サービスから来ています。本プロジェクトはその合法性や正確性に責任を負いません。'),
      h('2. 著作権データ'),
      p('2.1 本プロジェクトの使用中に著作権データが生じることがあります。本プロジェクトはその所有権を持ちません。権利侵害を避けるため、ユーザーは本プロジェクトの使用中に生じた著作権データを ', { bold: '24 時間以内' }, ' に削除しなければなりません。'),
      h('3. 音楽プラットフォームの別名'),
      p('3.1 本プロジェクト内の公式音楽プラットフォームの別名は、プロジェクト内での呼び名にすぎず、悪意はありません。公式音楽プラットフォームが不適切と考える場合は、本プロジェクトに連絡すれば変更または削除します。'),
      h('4. リソースの使用'),
      p('4.1 本プロジェクトで使われているフォントや画像などを含むがこれに限らない一部のリソースは、インターネットから得たものです。権利を侵害しているものがあれば、本プロジェクトに連絡すれば削除します。'),
      h('5. 免責事項'),
      p('5.1 この契約、または本プロジェクトの使用や使用不能から生じる、あらゆる種類の直接的・間接的・特別・偶発的・結果的損害（営業権の喪失、業務の停止、コンピューターの故障や誤動作、その他あらゆる商業上の損害や損失を含むがこれに限らない）は、ユーザーが責任を負います。'),
      h('6. 使用の制限'),
      p('6.1 本プロジェクトは完全に無料で、世界中の人が技術を学び交流するために ', { link: 'repo', text: 'GitHub' }, ' でオープンソースとして公開されています。本プロジェクトは、その技術が各地の法令に適合することを保証しません。'),
      p('6.2 ', { bold: '各地の法令に反する形で本プロジェクトを使わないでください。' }, '各地の法令が認めない状況で本プロジェクトを使ったことによる違反は、ユーザーが知っていたかどうかにかかわらずユーザーが負うものとし、本プロジェクトはそれによる直接的・間接的・特別・偶発的・結果的な責任を一切負いません。'),
      h('7. 著作権'),
      p('7.1 音楽プラットフォームの運営は簡単ではありません。著作権を尊重し、公式プラットフォームを応援してください。'),
      h('8. 非営利'),
      p('8.1 本プロジェクトは技術的な実現可能性の探求と研究のためだけのものです。商業的な協力（広告などを含むがこれに限らない）や寄付は受け付けません。'),
      h('9. 同意'),
      p('9.1 本プロジェクトを使うことは、この契約に同意したことを意味します。'),
      p('* この契約は予告なく更新されることがあります。最新版はオープンソースのリポジトリで確認できます。'),
      p('* この翻訳は参考のためのものです。英語版と内容が異なる場合は、英語版が優先されます。'),
    ],
    acceptTip: 'あなた（ユーザー）が上記の契約に同意する場合は「同意する」を押してください。同意しない場合は「同意しない」を押して終了し、このソフトウェアのすべてのデータを削除してください。',
  }),
  ko: (license, platform) => ({
    title: '라이선스 계약',
    mustAgree: '이 소프트웨어를 사용하기 전에 당신(사용자)은 이 계약에 동의해야 합니다.',
    paragraphs: [
      p('이 프로젝트는 ', { link: 'license', text: license }, ' 라이선스로 배포됩니다. 아래 계약은 이를 보완하며, 서로 충돌할 경우 아래 계약이 우선합니다.'),
      p('용어 정의: 이 계약에서 "본 프로젝트"는 LX Music+ ', platform, ' 프로젝트(LX Music의 비공식 포크)를, "사용자"는 이 계약에 동의한 사람을, "공식 음악 플랫폼"은 본 프로젝트가 보여주는 데이터의 각 공식 플랫폼을, "저작권 데이터"는 이미지, 오디오, 이름 등을 포함하되 이에 국한되지 않는, 타인이 저작권을 가진 데이터를 말합니다.'),
      h('1. 데이터 출처'),
      p('1.1 공식 플랫폼의 온라인 데이터는 공개 서버에서 가져온 것(로그인하지 않은 상태로 공식 앱에서 보이는 것과 같은 데이터)을 간단히 걸러내고 합쳐서 보여줍니다. 본 프로젝트는 그 데이터의 합법성이나 정확성에 책임지지 않습니다.'),
      p('1.2 본 프로젝트는 스스로 오디오를 가져오는 기능이 없으며, 내장된 소스도 없습니다. 본 프로젝트가 사용하는 온라인 오디오는 사용자가 "설정 → 소스"에서 직접 추가한 소스(음악 API, 소스 애드온)가 돌려주는 링크에서 옵니다. 곡을 재생할 때 본 프로젝트는 곡 제목, 아티스트 등의 정보를 소스에 전달할 뿐이며, 소스가 링크를 돌려주면 그것을 그 곡의 오디오로 사용합니다. 그 오디오가 올바른지 확인할 수 없으므로, 재생되는 오디오가 곡과 다르거나 재생되지 않을 수 있습니다. 서드파티 소스는 각 제작자가 만들고 호스팅하며, 본 프로젝트는 이에 책임지지 않습니다.'),
      p('1.3 공식 플랫폼에서 오지 않은 데이터("내 서재"의 목록 등)는 사용자의 시스템이나 사용자가 연결한 동기화 서비스에서 옵니다. 본 프로젝트는 그 합법성이나 정확성에 책임지지 않습니다.'),
      h('2. 저작권 데이터'),
      p('2.1 본 프로젝트를 사용하는 동안 저작권 데이터가 생길 수 있습니다. 본 프로젝트는 그 소유권을 갖지 않습니다. 권리 침해를 피하기 위해 사용자는 본 프로젝트를 사용하며 생긴 저작권 데이터를 ', { bold: '24시간 이내에' }, ' 삭제해야 합니다.'),
      h('3. 음악 플랫폼 별칭'),
      p('3.1 본 프로젝트의 공식 음악 플랫폼 별칭은 프로젝트 안에서 쓰는 이름일 뿐이며 악의가 없습니다. 공식 음악 플랫폼이 부적절하다고 생각하면 본 프로젝트에 연락해 변경하거나 삭제할 수 있습니다.'),
      h('4. 리소스 사용'),
      p('4.1 본 프로젝트에서 사용하는 글꼴, 이미지 등을 포함하되 이에 국한되지 않는 일부 리소스는 인터넷에서 가져온 것입니다. 권리를 침해하는 것이 있다면 본 프로젝트에 연락해 삭제할 수 있습니다.'),
      h('5. 면책 조항'),
      p('5.1 이 계약 또는 본 프로젝트의 사용이나 사용 불능으로 인해 발생하는 모든 종류의 직접적, 간접적, 특별, 부수적 또는 결과적 손해(영업권 손실, 업무 중단, 컴퓨터 고장 또는 오작동, 기타 모든 상업적 손해나 손실을 포함하되 이에 국한되지 않음)는 사용자가 책임집니다.'),
      h('6. 사용 제한'),
      p('6.1 본 프로젝트는 완전히 무료이며, 전 세계 사람들이 기술을 배우고 교류할 수 있도록 ', { link: 'repo', text: 'GitHub' }, '에 오픈 소스로 공개되어 있습니다. 본 프로젝트는 그 기술이 각 지역의 법령에 맞는다고 보장하지 않습니다.'),
      p('6.2 ', { bold: '각 지역의 법령을 위반하는 방식으로 본 프로젝트를 사용하지 마세요.' }, ' 각 지역의 법령이 허용하지 않는 상황에서 본 프로젝트를 사용해 생긴 위반은 사용자가 알았든 몰랐든 사용자가 책임지며, 본 프로젝트는 그로 인한 직접적, 간접적, 특별, 부수적 또는 결과적 책임을 지지 않습니다.'),
      h('7. 저작권'),
      p('7.1 음악 플랫폼을 운영하는 것은 쉽지 않습니다. 저작권을 존중하고 공식 플랫폼을 지원해 주세요.'),
      h('8. 비상업성'),
      p('8.1 본 프로젝트는 기술적 실현 가능성을 탐구하고 연구하기 위한 것입니다. 상업적 협력(광고 등을 포함하되 이에 국한되지 않음)이나 기부는 받지 않습니다.'),
      h('9. 동의'),
      p('9.1 본 프로젝트를 사용하면 이 계약에 동의한 것으로 봅니다.'),
      p('* 이 계약은 예고 없이 업데이트될 수 있으며, 최신 버전은 오픈 소스 저장소에서 볼 수 있습니다.'),
      p('* 이 번역은 참고용입니다. 영어판과 내용이 다를 경우 영어판이 우선합니다.'),
    ],
    acceptTip: '당신(사용자)이 위 계약에 동의하면 "동의"를 누르세요. 동의하지 않으면 "거부"를 눌러 종료하고 이 소프트웨어의 모든 데이터를 삭제하세요.',
  }),
  es: (license, platform) => ({
    title: 'Acuerdo de licencia',
    mustAgree: 'Tú (el usuario) tienes que aceptar este acuerdo antes de usar este software.',
    paragraphs: [
      p('Este proyecto se publica bajo la ', { link: 'license', text: license }, '. El siguiente acuerdo la complementa; si se contradicen, prevalece el siguiente acuerdo.'),
      p('Definiciones: en este acuerdo, «este proyecto» es el proyecto LX Music+ ', platform, ', un fork no oficial de LX Music; «el usuario» es la persona que acepta este acuerdo; «plataformas musicales oficiales» son las plataformas oficiales cuyos datos muestra este proyecto; «datos con copyright» son datos cuyo copyright pertenece a otros, incluidos, entre otros, imágenes, audio y nombres.'),
      h('1. Origen de los datos'),
      p('1.1 Los datos en línea de las plataformas oficiales se obtienen de sus servidores públicos (los mismos datos que muestran sus apps sin iniciar sesión) y se filtran y combinan para mostrarlos. Este proyecto no se hace responsable de la legalidad ni de la exactitud de esos datos.'),
      p('1.2 Este proyecto no puede obtener audio por sí mismo y no incluye ninguna fuente. El audio en línea que usa procede de los enlaces que devuelven las fuentes que el usuario añade en Ajustes → Fuentes (API de música y complementos de fuente). Para reproducir una canción, este proyecto solo pasa a una fuente el nombre de la canción, el artista e información similar; si la fuente devuelve un enlace, este proyecto lo usa como el audio de la canción. No puede comprobar si ese audio es correcto, así que el audio reproducido puede no coincidir con la canción o no reproducirse. Las fuentes de terceros las crean y alojan sus autores; este proyecto no se hace responsable de ellas.'),
      p('1.3 Los datos que no proceden de plataformas oficiales (por ejemplo, las listas de la Biblioteca) proceden del sistema del usuario o de los servicios de sincronización a los que se conecta. Este proyecto no se hace responsable de su legalidad ni de su exactitud.'),
      h('2. Datos con copyright'),
      p('2.1 Al usar este proyecto pueden generarse datos con copyright. Este proyecto no es su propietario. Para evitar infracciones, el usuario debe borrar los datos con copyright generados al usar este proyecto ', { bold: 'en un plazo de 24 horas' }, '.'),
      h('3. Alias de las plataformas musicales'),
      p('3.1 Los alias de las plataformas musicales oficiales en este proyecto son solo nombres usados dentro del proyecto y no tienen mala intención. Si una plataforma musical oficial los considera inapropiados, puede contactar con este proyecto para cambiarlos o quitarlos.'),
      h('4. Uso de recursos'),
      p('4.1 Algunos recursos usados en este proyecto, incluidos, entre otros, fuentes tipográficas e imágenes, proceden de internet. Si algo infringe tus derechos, contacta con este proyecto para que lo quite.'),
      h('5. Exención de responsabilidad'),
      p('5.1 El usuario es responsable de cualquier daño directo, indirecto, especial, incidental o consecuente de cualquier tipo derivado de este acuerdo o del uso o la imposibilidad de usar este proyecto (incluidos, entre otros, la pérdida de fondo de comercio, la interrupción del trabajo, el fallo o mal funcionamiento del ordenador, o cualquier otro daño o pérdida comercial).'),
      h('6. Restricciones'),
      p('6.1 Este proyecto es totalmente gratuito y se publica como código abierto en ', { link: 'repo', text: 'GitHub' }, ' para que personas de todo el mundo aprendan e intercambien conocimientos técnicos. Este proyecto no garantiza que su tecnología cumpla las leyes y normas locales.'),
      p('6.2 ', { bold: 'No uses este proyecto donde infrinja las leyes y normas locales.' }, ' El usuario asume cualquier infracción causada por usar este proyecto donde las leyes y normas locales no lo permitan, lo supiera o no; este proyecto no asume ninguna responsabilidad directa, indirecta, especial, incidental o consecuente por ello.'),
      h('7. Copyright'),
      p('7.1 Mantener una plataforma musical no es fácil. Respeta el copyright y apoya a las plataformas oficiales.'),
      h('8. Sin fines comerciales'),
      p('8.1 Este proyecto sirve solo para explorar e investigar la viabilidad técnica. No acepta colaboraciones comerciales (incluida, entre otras, la publicidad) ni donaciones.'),
      h('9. Aceptación'),
      p('9.1 Usar este proyecto significa que aceptas este acuerdo.'),
      p('* Este acuerdo puede actualizarse sin previo aviso; la versión vigente está en el repositorio de código abierto.'),
      p('* Esta traducción se ofrece por comodidad; si difiere de la versión en inglés, prevalece la versión en inglés.'),
    ],
    acceptTip: 'Si tú (el usuario) aceptas el acuerdo anterior, pulsa «Aceptar». Si no, pulsa «Rechazar» para salir y borra todos los datos de este software.',
  }),
  pt: (license, platform) => ({
    title: 'Contrato de licença',
    mustAgree: 'Você (o usuário) precisa aceitar este contrato antes de usar este software.',
    paragraphs: [
      p('Este projeto é distribuído sob a ', { link: 'license', text: license }, '. O contrato a seguir a complementa; em caso de conflito, prevalece o contrato a seguir.'),
      p('Definições: neste contrato, "este projeto" é o projeto LX Music+ ', platform, ', um fork não oficial do LX Music; "o usuário" é a pessoa que aceita este contrato; "plataformas musicais oficiais" são as plataformas oficiais cujos dados este projeto mostra; "dados protegidos por direitos autorais" são dados cujos direitos autorais pertencem a terceiros, incluindo, entre outros, imagens, áudio e nomes.'),
      h('1. Origem dos dados'),
      p('1.1 Os dados on-line das plataformas oficiais são obtidos dos servidores públicos delas (os mesmos dados que os apps oficiais mostram sem login), depois filtrados e combinados para exibição. Este projeto não se responsabiliza pela legalidade nem pela exatidão desses dados.'),
      p('1.2 Este projeto não consegue obter áudio sozinho e não tem nenhuma fonte embutida. O áudio on-line que ele usa vem dos links devolvidos pelas fontes que o usuário adiciona em Configurações → Fontes (APIs de música e complementos de fonte). Para tocar uma música, este projeto só passa a uma fonte o nome da música, o artista e informações parecidas; se a fonte devolver um link, este projeto o usa como o áudio da música. Não é possível verificar se esse áudio está correto, então o áudio tocado pode não corresponder à música ou não tocar. Fontes de terceiros são feitas e hospedadas pelos autores; este projeto não se responsabiliza por elas.'),
      p('1.3 Os dados que não vêm de plataformas oficiais (por exemplo, as listas da Biblioteca) vêm do sistema do usuário ou dos serviços de sincronização aos quais ele se conecta. Este projeto não se responsabiliza pela legalidade nem pela exatidão deles.'),
      h('2. Dados protegidos por direitos autorais'),
      p('2.1 Dados protegidos por direitos autorais podem ser gerados durante o uso deste projeto. Este projeto não é dono deles. Para evitar violações, o usuário deve apagar os dados protegidos gerados durante o uso deste projeto ', { bold: 'em até 24 horas' }, '.'),
      h('3. Apelidos das plataformas musicais'),
      p('3.1 Os apelidos das plataformas musicais oficiais neste projeto são apenas nomes usados dentro do projeto, sem má intenção. Se uma plataforma musical oficial achá-los inadequados, pode entrar em contato com este projeto para alterá-los ou removê-los.'),
      h('4. Uso de recursos'),
      p('4.1 Alguns recursos usados neste projeto, incluindo, entre outros, fontes tipográficas e imagens, vêm da internet. Se algo violar seus direitos, entre em contato com este projeto para removê-lo.'),
      h('5. Isenção de responsabilidade'),
      p('5.1 O usuário é responsável por quaisquer danos diretos, indiretos, especiais, incidentais ou consequentes de qualquer tipo decorrentes deste contrato ou do uso ou da impossibilidade de uso deste projeto (incluindo, entre outros, perda de fundo de comércio, interrupção do trabalho, falha ou mau funcionamento do computador, ou quaisquer outros danos ou perdas comerciais).'),
      h('6. Restrições'),
      p('6.1 Este projeto é totalmente gratuito e publicado como código aberto no ', { link: 'repo', text: 'GitHub' }, ' para que pessoas do mundo todo aprendam e troquem conhecimento técnico. Este projeto não garante que sua tecnologia esteja de acordo com as leis e normas locais.'),
      p('6.2 ', { bold: 'Não use este projeto onde isso viole as leis e normas locais.' }, ' O usuário responde por qualquer violação causada pelo uso deste projeto onde as leis e normas locais não permitem, sabendo disso ou não; este projeto não assume nenhuma responsabilidade direta, indireta, especial, incidental ou consequente por isso.'),
      h('7. Direitos autorais'),
      p('7.1 Manter uma plataforma de música não é fácil. Respeite os direitos autorais e apoie as plataformas oficiais.'),
      h('8. Sem fins comerciais'),
      p('8.1 Este projeto serve apenas para explorar e pesquisar a viabilidade técnica. Não aceita parcerias comerciais (incluindo, entre outras, publicidade) nem doações.'),
      h('9. Aceitação'),
      p('9.1 Usar este projeto significa que você aceita este contrato.'),
      p('* Este contrato pode ser atualizado sem aviso; a versão atual está no repositório de código aberto.'),
      p('* Esta tradução é oferecida por conveniência; se divergir da versão em inglês, prevalece a versão em inglês.'),
    ],
    acceptTip: 'Se você (o usuário) aceita o contrato acima, toque em "Aceitar". Se não, toque em "Recusar" para sair e apague todos os dados deste software.',
  }),
  ru: (license, platform) => ({
    title: 'Лицензионное соглашение',
    mustAgree: 'Перед использованием этой программы вы (пользователь) должны принять это соглашение.',
    paragraphs: [
      p('Этот проект распространяется по лицензии ', { link: 'license', text: license }, '. Следующее соглашение дополняет её; при противоречии действует следующее соглашение.'),
      p('Определения: в этом соглашении «этот проект» — проект LX Music+ ', platform, ', неофициальный форк LX Music; «пользователь» — человек, принявший это соглашение; «официальные музыкальные платформы» — официальные платформы, данные которых показывает этот проект; «данные, защищённые авторским правом» — данные, авторские права на которые принадлежат другим, включая, помимо прочего, изображения, аудио и названия.'),
      h('1. Источники данных'),
      p('1.1 Онлайн-данные официальных платформ берутся с их публичных серверов (это те же данные, что показывают их приложения без входа в аккаунт), затем фильтруются и объединяются для показа. Этот проект не отвечает за законность и точность этих данных.'),
      p('1.2 Этот проект не может сам получать аудио и не содержит встроенных источников. Онлайн-аудио, которое он использует, берётся по ссылкам, которые возвращают источники, добавленные пользователем в разделе Настройки → Источники (Music API и дополнения-источники). Чтобы воспроизвести трек, этот проект лишь передаёт источнику название трека, исполнителя и подобные сведения; если источник возвращает ссылку, проект использует её как аудио трека. Проверить правильность этого аудио нельзя, поэтому воспроизводимое аудио может не совпадать с треком или не воспроизводиться. Сторонние источники создают и размещают их авторы; этот проект за них не отвечает.'),
      p('1.3 Данные не с официальных платформ (например, списки в Медиатеке) берутся из системы пользователя или из сервисов синхронизации, к которым он подключается. Этот проект не отвечает за их законность и точность.'),
      h('2. Данные, защищённые авторским правом'),
      p('2.1 При использовании этого проекта могут появляться данные, защищённые авторским правом. Этот проект ими не владеет. Чтобы избежать нарушений, пользователь должен удалять такие данные, появившиеся при использовании проекта, ', { bold: 'в течение 24 часов' }, '.'),
      h('3. Псевдонимы музыкальных платформ'),
      p('3.1 Псевдонимы официальных музыкальных платформ в этом проекте — лишь названия внутри проекта, без злого умысла. Если официальная музыкальная платформа считает их неуместными, она может связаться с проектом, чтобы их изменили или убрали.'),
      h('4. Использование ресурсов'),
      p('4.1 Некоторые ресурсы проекта, включая, помимо прочего, шрифты и изображения, взяты из интернета. Если что-то нарушает ваши права, свяжитесь с проектом, чтобы это убрали.'),
      h('5. Отказ от ответственности'),
      p('5.1 Пользователь несёт ответственность за любой прямой, косвенный, особый, случайный или последующий ущерб любого рода, возникший из этого соглашения или из использования либо невозможности использования этого проекта (включая, помимо прочего, потерю деловой репутации, остановку работы, сбой или неисправность компьютера и любой другой коммерческий ущерб или убытки).'),
      h('6. Ограничения'),
      p('6.1 Этот проект полностью бесплатен и опубликован с открытым исходным кодом на ', { link: 'repo', text: 'GitHub' }, ', чтобы люди по всему миру могли изучать технологии и обмениваться опытом. Проект не гарантирует, что его технологии соответствуют местным законам и нормам.'),
      p('6.2 ', { bold: 'Не используйте этот проект там, где это нарушает местные законы и нормы.' }, ' Пользователь отвечает за любые нарушения, вызванные использованием проекта там, где местные законы и нормы этого не допускают, знал он об этом или нет; проект не несёт за это никакой прямой, косвенной, особой, случайной или последующей ответственности.'),
      h('7. Авторское право'),
      p('7.1 Содержать музыкальную платформу непросто. Уважайте авторское право и поддерживайте официальные платформы.'),
      h('8. Некоммерческий характер'),
      p('8.1 Этот проект служит только для изучения и исследования технической осуществимости. Он не принимает коммерческое сотрудничество (включая, помимо прочего, рекламу) и пожертвования.'),
      h('9. Принятие'),
      p('9.1 Используя этот проект, вы принимаете это соглашение.'),
      p('* Соглашение может обновляться без уведомления; актуальная версия находится в репозитории с открытым исходным кодом.'),
      p('* Этот перевод дан для удобства; если он расходится с английской версией, действует английская версия.'),
    ],
    acceptTip: 'Если вы (пользователь) принимаете соглашение выше, нажмите «Принять». Если нет, нажмите «Отклонить», чтобы выйти, и удалите все данные этой программы.',
  }),
  vi: (license, platform) => ({
    title: 'Thỏa thuận cấp phép',
    mustAgree: 'Bạn (người dùng) cần đồng ý thỏa thuận này trước khi dùng phần mềm.',
    paragraphs: [
      p('Dự án này được phát hành theo giấy phép ', { link: 'license', text: license }, '. Thỏa thuận dưới đây bổ sung cho giấy phép đó; nếu có mâu thuẫn, thỏa thuận dưới đây được ưu tiên.'),
      p('Định nghĩa: trong thỏa thuận này, "dự án này" là dự án LX Music+ bản ', platform, ', một bản fork không chính thức của LX Music; "người dùng" là người đồng ý thỏa thuận này; "nền tảng âm nhạc chính thức" là các nền tảng chính thức có dữ liệu được dự án này hiển thị; "dữ liệu có bản quyền" là dữ liệu mà bản quyền thuộc về người khác, gồm nhưng không giới hạn ở hình ảnh, âm thanh và tên.'),
      h('1. Nguồn dữ liệu'),
      p('1.1 Dữ liệu trực tuyến của các nền tảng chính thức được lấy từ máy chủ công khai của họ (giống dữ liệu ứng dụng chính thức hiện khi chưa đăng nhập), rồi được lọc và gộp để hiển thị. Dự án này không chịu trách nhiệm về tính hợp pháp hay chính xác của dữ liệu đó.'),
      p('1.2 Dự án này không tự lấy được âm thanh và không tích hợp sẵn nguồn nào. Âm thanh trực tuyến mà dự án dùng đến từ các liên kết do nguồn mà người dùng tự thêm trong Cài đặt → Nguồn (Music API và tiện ích nguồn) trả về. Để phát một bài, dự án chỉ chuyển tên bài, nghệ sĩ và thông tin tương tự cho nguồn; nếu nguồn trả về một liên kết, dự án dùng nó làm âm thanh của bài. Dự án không kiểm tra được âm thanh đó có đúng không, nên âm thanh được phát có thể không khớp với bài hoặc không phát được. Nguồn bên thứ ba do tác giả của chúng làm và lưu trữ; dự án này không chịu trách nhiệm về chúng.'),
      p('1.3 Dữ liệu không đến từ nền tảng chính thức (ví dụ danh sách trong Thư viện) đến từ hệ thống của người dùng hoặc dịch vụ đồng bộ mà người dùng kết nối. Dự án này không chịu trách nhiệm về tính hợp pháp hay chính xác của chúng.'),
      h('2. Dữ liệu có bản quyền'),
      p('2.1 Trong khi dùng dự án này có thể phát sinh dữ liệu có bản quyền. Dự án này không sở hữu chúng. Để tránh vi phạm, người dùng phải xóa dữ liệu có bản quyền phát sinh khi dùng dự án ', { bold: 'trong vòng 24 giờ' }, '.'),
      h('3. Tên gọi khác của nền tảng âm nhạc'),
      p('3.1 Tên gọi khác của các nền tảng âm nhạc chính thức trong dự án chỉ là cách gọi trong dự án, không có ác ý. Nếu nền tảng âm nhạc chính thức thấy không phù hợp, có thể liên hệ dự án để đổi hoặc gỡ.'),
      h('4. Sử dụng tài nguyên'),
      p('4.1 Một số tài nguyên dùng trong dự án, gồm nhưng không giới hạn ở phông chữ và hình ảnh, lấy từ internet. Nếu có gì vi phạm quyền của bạn, hãy liên hệ dự án để gỡ.'),
      h('5. Miễn trừ trách nhiệm'),
      p('5.1 Người dùng chịu trách nhiệm về mọi thiệt hại trực tiếp, gián tiếp, đặc biệt, ngẫu nhiên hoặc hệ quả thuộc bất kỳ loại nào phát sinh từ thỏa thuận này hoặc từ việc dùng hay không dùng được dự án này (gồm nhưng không giới hạn ở mất uy tín, ngừng việc, hỏng hóc hay trục trặc máy tính, hoặc mọi thiệt hại, tổn thất thương mại khác).'),
      h('6. Giới hạn sử dụng'),
      p('6.1 Dự án này hoàn toàn miễn phí và được phát hành mã nguồn mở trên ', { link: 'repo', text: 'GitHub' }, ' để mọi người trên thế giới học hỏi và trao đổi kỹ thuật. Dự án không bảo đảm công nghệ của mình tuân thủ luật pháp và quy định địa phương.'),
      p('6.2 ', { bold: 'Đừng dùng dự án này ở nơi vi phạm luật pháp và quy định địa phương.' }, ' Người dùng chịu mọi vi phạm do dùng dự án ở nơi luật pháp và quy định địa phương không cho phép, dù có biết hay không; dự án này không chịu bất kỳ trách nhiệm trực tiếp, gián tiếp, đặc biệt, ngẫu nhiên hay hệ quả nào về việc đó.'),
      h('7. Bản quyền'),
      p('7.1 Vận hành một nền tảng âm nhạc không dễ. Hãy tôn trọng bản quyền và ủng hộ các nền tảng chính thức.'),
      h('8. Phi thương mại'),
      p('8.1 Dự án này chỉ nhằm khám phá và nghiên cứu tính khả thi về kỹ thuật. Dự án không nhận hợp tác thương mại (gồm nhưng không giới hạn ở quảng cáo) và không nhận quyên góp.'),
      h('9. Chấp nhận'),
      p('9.1 Dùng dự án này nghĩa là bạn chấp nhận thỏa thuận này.'),
      p('* Thỏa thuận này có thể được cập nhật mà không báo trước; phiên bản hiện hành có trong kho mã nguồn mở.'),
      p('* Bản dịch này chỉ để tiện theo dõi; nếu khác với bản tiếng Anh, bản tiếng Anh được ưu tiên.'),
    ],
    acceptTip: 'Nếu bạn (người dùng) đồng ý thỏa thuận trên, hãy nhấn "Đồng ý". Nếu không, hãy nhấn "Không đồng ý" để thoát và xóa toàn bộ dữ liệu của phần mềm này.',
  }),
  de: (license, platform) => ({
    title: 'Lizenzvereinbarung',
    mustAgree: 'Du (der Nutzer) musst dieser Vereinbarung zustimmen, bevor du diese Software verwendest.',
    paragraphs: [
      p('Dieses Projekt wird unter der ', { link: 'license', text: license }, ' veröffentlicht. Die folgende Vereinbarung ergänzt sie; bei Widersprüchen gilt die folgende Vereinbarung.'),
      p('Begriffe: In dieser Vereinbarung bezeichnet „dieses Projekt“ das Projekt LX Music+ ', platform, ', einen inoffiziellen Fork von LX Music; „der Nutzer“ die Person, die dieser Vereinbarung zustimmt; „offizielle Musikplattformen“ die offiziellen Plattformen, deren Daten dieses Projekt anzeigt; „urheberrechtlich geschützte Daten“ Daten, deren Urheberrecht anderen gehört, darunter unter anderem Bilder, Audio und Namen.'),
      h('1. Herkunft der Daten'),
      p('1.1 Die Online-Daten der offiziellen Plattformen werden von deren öffentlichen Servern abgerufen (dieselben Daten, die ihre Apps ohne Anmeldung zeigen), dann gefiltert und für die Anzeige zusammengeführt. Dieses Projekt ist für die Rechtmäßigkeit und Richtigkeit dieser Daten nicht verantwortlich.'),
      p('1.2 Dieses Projekt kann selbst kein Audio beschaffen und enthält keine eingebaute Quelle. Das Online-Audio, das es verwendet, stammt aus den Links, die die vom Nutzer unter Einstellungen → Quellen hinzugefügten Quellen (Music APIs und Quellen-Add-ons) zurückgeben. Um einen Song abzuspielen, übergibt dieses Projekt einer Quelle nur den Songtitel, den Künstler und ähnliche Angaben; gibt die Quelle einen Link zurück, verwendet das Projekt ihn als Audio des Songs. Ob dieses Audio stimmt, kann es nicht prüfen; das abgespielte Audio kann daher vom Song abweichen oder nicht abspielbar sein. Quellen von Drittanbietern werden von ihren Autoren erstellt und gehostet; dieses Projekt ist für sie nicht verantwortlich.'),
      p('1.3 Daten, die nicht von offiziellen Plattformen stammen (zum Beispiel die Listen in der Mediathek), kommen aus dem System des Nutzers oder aus den Synchronisierungsdiensten, mit denen er sich verbindet. Dieses Projekt ist für ihre Rechtmäßigkeit und Richtigkeit nicht verantwortlich.'),
      h('2. Urheberrechtlich geschützte Daten'),
      p('2.1 Bei der Nutzung dieses Projekts können urheberrechtlich geschützte Daten entstehen. Dieses Projekt besitzt sie nicht. Um Rechtsverletzungen zu vermeiden, muss der Nutzer die bei der Nutzung entstandenen urheberrechtlich geschützten Daten ', { bold: 'innerhalb von 24 Stunden' }, ' löschen.'),
      h('3. Aliasnamen der Musikplattformen'),
      p('3.1 Die Aliasnamen der offiziellen Musikplattformen in diesem Projekt sind nur projektinterne Bezeichnungen ohne böse Absicht. Hält eine offizielle Musikplattform sie für unpassend, kann sie dieses Projekt kontaktieren, um sie ändern oder entfernen zu lassen.'),
      h('4. Verwendung von Ressourcen'),
      p('4.1 Einige in diesem Projekt verwendete Ressourcen, darunter unter anderem Schriftarten und Bilder, stammen aus dem Internet. Falls etwas deine Rechte verletzt, kontaktiere dieses Projekt, damit es entfernt wird.'),
      h('5. Haftungsausschluss'),
      p('5.1 Der Nutzer ist verantwortlich für alle direkten, indirekten, besonderen, zufälligen oder Folgeschäden jeglicher Art, die aus dieser Vereinbarung oder aus der Nutzung oder Nichtnutzbarkeit dieses Projekts entstehen (darunter unter anderem Verlust von Geschäftswert, Arbeitsausfall, Computerausfall oder -fehlfunktion sowie alle sonstigen kommerziellen Schäden oder Verluste).'),
      h('6. Einschränkungen'),
      p('6.1 Dieses Projekt ist völlig kostenlos und als Open Source auf ', { link: 'repo', text: 'GitHub' }, ' veröffentlicht, damit Menschen auf der ganzen Welt technisch lernen und sich austauschen können. Dieses Projekt garantiert nicht, dass seine Technik den örtlichen Gesetzen und Vorschriften entspricht.'),
      p('6.2 ', { bold: 'Verwende dieses Projekt nicht, wo dies gegen örtliche Gesetze und Vorschriften verstößt.' }, ' Der Nutzer trägt jeden Verstoß, der durch die Nutzung dieses Projekts entsteht, wo örtliche Gesetze und Vorschriften dies nicht erlauben, ob wissentlich oder nicht; dieses Projekt übernimmt dafür keinerlei direkte, indirekte, besondere, zufällige oder Folgehaftung.'),
      h('7. Urheberrecht'),
      p('7.1 Eine Musikplattform zu betreiben ist nicht leicht. Bitte respektiere das Urheberrecht und unterstütze die offiziellen Plattformen.'),
      h('8. Nicht kommerziell'),
      p('8.1 Dieses Projekt dient nur der Erkundung und Erforschung der technischen Machbarkeit. Es nimmt keine kommerzielle Zusammenarbeit (darunter unter anderem Werbung) und keine Spenden an.'),
      h('9. Zustimmung'),
      p('9.1 Wer dieses Projekt verwendet, stimmt dieser Vereinbarung zu.'),
      p('* Diese Vereinbarung kann ohne Ankündigung aktualisiert werden; die aktuelle Fassung steht im Open-Source-Repository.'),
      p('* Diese Übersetzung dient nur der Orientierung; weicht sie von der englischen Fassung ab, gilt die englische Fassung.'),
    ],
    acceptTip: 'Wenn du (der Nutzer) der obigen Vereinbarung zustimmst, drücke „Akzeptieren“. Wenn nicht, drücke „Ablehnen“, um die App zu beenden, und lösche alle Daten dieser Software.',
  }),
  fr: (license, platform) => ({
    title: 'Contrat de licence',
    mustAgree: 'Vous (l’utilisateur) devez accepter ce contrat avant d’utiliser ce logiciel.',
    paragraphs: [
      p('Ce projet est publié sous la ', { link: 'license', text: license }, '. Le contrat suivant la complète ; en cas de contradiction, le contrat suivant prévaut.'),
      p('Définitions : dans ce contrat, « ce projet » désigne le projet LX Music+ ', platform, ', un fork non officiel de LX Music ; « l’utilisateur » désigne la personne qui accepte ce contrat ; « plateformes musicales officielles » désigne les plateformes officielles dont ce projet affiche les données ; « données protégées » désigne des données dont le droit d’auteur appartient à autrui, notamment des images, de l’audio et des noms.'),
      h('1. Origine des données'),
      p('1.1 Les données en ligne des plateformes officielles sont récupérées sur leurs serveurs publics (les mêmes données que leurs applis affichent sans connexion), puis filtrées et combinées pour l’affichage. Ce projet n’est pas responsable de la légalité ni de l’exactitude de ces données.'),
      p('1.2 Ce projet ne peut pas obtenir d’audio par lui-même et n’inclut aucune source. L’audio en ligne qu’il utilise provient des liens renvoyés par les sources que l’utilisateur ajoute dans Paramètres → Sources (API musicales et modules de source). Pour lire un titre, ce projet transmet seulement à une source le nom du titre, l’artiste et des informations similaires ; si la source renvoie un lien, ce projet l’utilise comme audio du titre. Il ne peut pas vérifier que cet audio est correct : l’audio lu peut donc ne pas correspondre au titre, ou ne pas se lire. Les sources tierces sont créées et hébergées par leurs auteurs ; ce projet n’en est pas responsable.'),
      p('1.3 Les données qui ne viennent pas des plateformes officielles (par exemple les listes de la Bibliothèque) proviennent du système de l’utilisateur ou des services de synchronisation auxquels il se connecte. Ce projet n’est pas responsable de leur légalité ni de leur exactitude.'),
      h('2. Données protégées'),
      p('2.1 Des données protégées peuvent être produites lors de l’utilisation de ce projet. Ce projet n’en est pas propriétaire. Pour éviter toute violation, l’utilisateur doit supprimer les données protégées produites lors de l’utilisation de ce projet ', { bold: 'sous 24 heures' }, '.'),
      h('3. Surnoms des plateformes musicales'),
      p('3.1 Les surnoms des plateformes musicales officielles dans ce projet ne sont que des noms internes, sans mauvaise intention. Si une plateforme musicale officielle les juge inappropriés, elle peut contacter ce projet pour les faire modifier ou retirer.'),
      h('4. Utilisation de ressources'),
      p('4.1 Certaines ressources utilisées dans ce projet, notamment des polices et des images, proviennent d’internet. Si quelque chose porte atteinte à vos droits, contactez ce projet pour le faire retirer.'),
      h('5. Exclusion de responsabilité'),
      p('5.1 L’utilisateur est responsable de tout dommage direct, indirect, spécial, accessoire ou consécutif de quelque nature que ce soit découlant de ce contrat ou de l’utilisation ou de l’impossibilité d’utiliser ce projet (notamment perte de clientèle, arrêt de travail, panne ou dysfonctionnement informatique, ou tout autre dommage ou perte commerciale).'),
      h('6. Restrictions'),
      p('6.1 Ce projet est entièrement gratuit et publié en open source sur ', { link: 'repo', text: 'GitHub' }, ' pour permettre à chacun dans le monde d’apprendre et d’échanger sur la technique. Ce projet ne garantit pas que sa technique respecte les lois et règlements locaux.'),
      p('6.2 ', { bold: 'N’utilisez pas ce projet là où cela enfreint les lois et règlements locaux.' }, ' L’utilisateur assume toute infraction causée par l’utilisation de ce projet là où les lois et règlements locaux ne le permettent pas, qu’il le sache ou non ; ce projet n’assume aucune responsabilité directe, indirecte, spéciale, accessoire ou consécutive à ce titre.'),
      h('7. Droit d’auteur'),
      p('7.1 Faire vivre une plateforme musicale n’est pas facile. Respectez le droit d’auteur et soutenez les plateformes officielles.'),
      h('8. Non commercial'),
      p('8.1 Ce projet sert uniquement à explorer et étudier la faisabilité technique. Il n’accepte aucune collaboration commerciale (notamment la publicité) ni aucun don.'),
      h('9. Acceptation'),
      p('9.1 Utiliser ce projet signifie que vous acceptez ce contrat.'),
      p('* Ce contrat peut être mis à jour sans préavis ; la version en vigueur se trouve dans le dépôt open source.'),
      p('* Cette traduction est fournie pour plus de commodité ; en cas de divergence avec la version anglaise, la version anglaise prévaut.'),
    ],
    acceptTip: 'Si vous (l’utilisateur) acceptez le contrat ci-dessus, appuyez sur « Accepter ». Sinon, appuyez sur « Refuser » pour quitter, et supprimez toutes les données de ce logiciel.',
  }),
  it: (license, platform) => ({
    title: 'Contratto di licenza',
    mustAgree: 'Tu (l’utente) devi accettare questo contratto prima di usare questo software.',
    paragraphs: [
      p('Questo progetto è distribuito con la ', { link: 'license', text: license }, '. Il contratto seguente la integra; in caso di conflitto prevale il contratto seguente.'),
      p('Definizioni: in questo contratto, «questo progetto» indica il progetto LX Music+ ', platform, ', un fork non ufficiale di LX Music; «l’utente» indica la persona che accetta questo contratto; «piattaforme musicali ufficiali» indica le piattaforme ufficiali di cui questo progetto mostra i dati; «dati protetti da copyright» indica dati il cui copyright appartiene ad altri, inclusi, a titolo esemplificativo, immagini, audio e nomi.'),
      h('1. Origine dei dati'),
      p('1.1 I dati online delle piattaforme ufficiali vengono presi dai loro server pubblici (gli stessi dati che le loro app mostrano senza accesso), poi filtrati e combinati per la visualizzazione. Questo progetto non è responsabile della legalità né dell’esattezza di quei dati.'),
      p('1.2 Questo progetto non può ottenere audio da solo e non include alcuna fonte. L’audio online che usa proviene dai link restituiti dalle fonti che l’utente aggiunge in Impostazioni → Fonti (API musicali e componenti aggiuntivi delle fonti). Per riprodurre un brano, questo progetto passa a una fonte solo il titolo, l’artista e informazioni simili; se la fonte restituisce un link, il progetto lo usa come audio del brano. Non può verificare che quell’audio sia corretto, quindi l’audio riprodotto potrebbe non corrispondere al brano o non essere riproducibile. Le fonti di terze parti sono create e ospitate dai loro autori; questo progetto non ne è responsabile.'),
      p('1.3 I dati che non provengono dalle piattaforme ufficiali (per esempio le liste della Libreria) provengono dal sistema dell’utente o dai servizi di sincronizzazione a cui si collega. Questo progetto non è responsabile della loro legalità né della loro esattezza.'),
      h('2. Dati protetti da copyright'),
      p('2.1 Usando questo progetto possono generarsi dati protetti da copyright. Questo progetto non ne è proprietario. Per evitare violazioni, l’utente deve eliminare i dati protetti generati durante l’uso del progetto ', { bold: 'entro 24 ore' }, '.'),
      h('3. Soprannomi delle piattaforme musicali'),
      p('3.1 I soprannomi delle piattaforme musicali ufficiali in questo progetto sono solo nomi usati all’interno del progetto, senza cattive intenzioni. Se una piattaforma musicale ufficiale li ritiene inappropriati, può contattare questo progetto per farli cambiare o rimuovere.'),
      h('4. Uso delle risorse'),
      p('4.1 Alcune risorse usate in questo progetto, inclusi, a titolo esemplificativo, caratteri e immagini, provengono da internet. Se qualcosa viola i tuoi diritti, contatta questo progetto per farlo rimuovere.'),
      h('5. Esclusione di responsabilità'),
      p('5.1 L’utente è responsabile di qualsiasi danno diretto, indiretto, speciale, incidentale o consequenziale di qualsiasi natura derivante da questo contratto o dall’uso o dall’impossibilità di usare questo progetto (inclusi, a titolo esemplificativo, perdita di avviamento, interruzione del lavoro, guasto o malfunzionamento del computer, o qualsiasi altro danno o perdita commerciale).'),
      h('6. Limitazioni'),
      p('6.1 Questo progetto è completamente gratuito e pubblicato come open source su ', { link: 'repo', text: 'GitHub' }, ' perché persone di tutto il mondo possano imparare e scambiarsi conoscenze tecniche. Questo progetto non garantisce che la sua tecnologia rispetti le leggi e i regolamenti locali.'),
      p('6.2 ', { bold: 'Non usare questo progetto dove ciò viola le leggi e i regolamenti locali.' }, ' L’utente risponde di qualsiasi violazione causata dall’uso del progetto dove le leggi e i regolamenti locali non lo consentono, che ne fosse consapevole o no; questo progetto non si assume alcuna responsabilità diretta, indiretta, speciale, incidentale o consequenziale per questo.'),
      h('7. Copyright'),
      p('7.1 Gestire una piattaforma musicale non è facile. Rispetta il copyright e sostieni le piattaforme ufficiali.'),
      h('8. Non commerciale'),
      p('8.1 Questo progetto serve solo a esplorare e studiare la fattibilità tecnica. Non accetta collaborazioni commerciali (inclusa, a titolo esemplificativo, la pubblicità) né donazioni.'),
      h('9. Accettazione'),
      p('9.1 Usare questo progetto significa accettare questo contratto.'),
      p('* Questo contratto può essere aggiornato senza preavviso; la versione in vigore è nel repository open source.'),
      p('* Questa traduzione è fornita per comodità; se differisce dalla versione inglese, prevale la versione inglese.'),
    ],
    acceptTip: 'Se tu (l’utente) accetti il contratto qui sopra, premi «Accetta». Altrimenti premi «Rifiuta» per uscire ed elimina tutti i dati di questo software.',
  }),
  pl: (license, platform) => ({
    title: 'Umowa licencyjna',
    mustAgree: 'Przed użyciem tego programu Ty (użytkownik) musisz zaakceptować tę umowę.',
    paragraphs: [
      p('Ten projekt jest udostępniany na licencji ', { link: 'license', text: license }, '. Poniższa umowa ją uzupełnia; w razie sprzeczności obowiązuje poniższa umowa.'),
      p('Definicje: w tej umowie „ten projekt” oznacza projekt LX Music+ ', platform, ', nieoficjalny fork LX Music; „użytkownik” oznacza osobę, która akceptuje tę umowę; „oficjalne platformy muzyczne” oznaczają oficjalne platformy, których dane pokazuje ten projekt; „dane chronione prawem autorskim” oznaczają dane, do których prawa autorskie należą do innych, w tym m.in. obrazy, dźwięk i nazwy.'),
      h('1. Pochodzenie danych'),
      p('1.1 Dane online oficjalnych platform są pobierane z ich publicznych serwerów (to te same dane, które ich aplikacje pokazują bez logowania), a następnie filtrowane i łączone do wyświetlenia. Ten projekt nie odpowiada za legalność ani poprawność tych danych.'),
      p('1.2 Ten projekt nie potrafi sam pozyskać dźwięku i nie ma wbudowanego źródła. Dźwięk online, którego używa, pochodzi z linków zwracanych przez źródła dodane przez użytkownika w Ustawienia → Źródła (Music API i dodatki źródeł). Aby odtworzyć utwór, ten projekt przekazuje źródłu tylko tytuł utworu, wykonawcę i podobne informacje; jeśli źródło zwróci link, projekt używa go jako dźwięku utworu. Nie może sprawdzić, czy ten dźwięk jest właściwy, więc odtwarzany dźwięk może nie pasować do utworu albo się nie odtworzyć. Źródła zewnętrzne tworzą i udostępniają ich autorzy; ten projekt za nie nie odpowiada.'),
      p('1.3 Dane, które nie pochodzą z oficjalnych platform (np. listy w Bibliotece), pochodzą z systemu użytkownika lub z usług synchronizacji, z którymi się łączy. Ten projekt nie odpowiada za ich legalność ani poprawność.'),
      h('2. Dane chronione prawem autorskim'),
      p('2.1 Podczas korzystania z tego projektu mogą powstawać dane chronione prawem autorskim. Ten projekt nie jest ich właścicielem. Aby uniknąć naruszeń, użytkownik musi usunąć dane chronione powstałe podczas korzystania z projektu ', { bold: 'w ciągu 24 godzin' }, '.'),
      h('3. Przydomki platform muzycznych'),
      p('3.1 Przydomki oficjalnych platform muzycznych w tym projekcie to tylko nazwy używane wewnątrz projektu, bez złych intencji. Jeśli oficjalna platforma muzyczna uzna je za niestosowne, może skontaktować się z projektem, aby je zmienić lub usunąć.'),
      h('4. Wykorzystanie zasobów'),
      p('4.1 Niektóre zasoby użyte w tym projekcie, w tym m.in. czcionki i obrazy, pochodzą z internetu. Jeśli coś narusza Twoje prawa, skontaktuj się z projektem, aby to usunąć.'),
      h('5. Wyłączenie odpowiedzialności'),
      p('5.1 Użytkownik odpowiada za wszelkie bezpośrednie, pośrednie, szczególne, przypadkowe lub wynikowe szkody dowolnego rodzaju wynikające z tej umowy albo z korzystania lub niemożności korzystania z tego projektu (w tym m.in. utratę renomy, przestój w pracy, awarię lub nieprawidłowe działanie komputera oraz wszelkie inne szkody lub straty handlowe).'),
      h('6. Ograniczenia'),
      p('6.1 Ten projekt jest całkowicie darmowy i udostępniony jako open source na ', { link: 'repo', text: 'GitHub' }, ', aby ludzie na całym świecie mogli uczyć się i wymieniać wiedzą techniczną. Ten projekt nie gwarantuje, że jego technologia jest zgodna z lokalnym prawem i przepisami.'),
      p('6.2 ', { bold: 'Nie używaj tego projektu tam, gdzie narusza to lokalne prawo i przepisy.' }, ' Użytkownik odpowiada za wszelkie naruszenia wynikające z używania projektu tam, gdzie lokalne prawo i przepisy na to nie pozwalają, niezależnie od tego, czy o tym wiedział; ten projekt nie ponosi z tego tytułu żadnej bezpośredniej, pośredniej, szczególnej, przypadkowej ani wynikowej odpowiedzialności.'),
      h('7. Prawo autorskie'),
      p('7.1 Utrzymanie platformy muzycznej nie jest łatwe. Szanuj prawa autorskie i wspieraj oficjalne platformy.'),
      h('8. Charakter niekomercyjny'),
      p('8.1 Ten projekt służy wyłącznie do poznawania i badania wykonalności technicznej. Nie przyjmuje współpracy komercyjnej (w tym m.in. reklam) ani darowizn.'),
      h('9. Akceptacja'),
      p('9.1 Korzystanie z tego projektu oznacza akceptację tej umowy.'),
      p('* Ta umowa może zostać zaktualizowana bez uprzedzenia; aktualna wersja znajduje się w repozytorium open source.'),
      p('* To tłumaczenie ma charakter pomocniczy; w razie rozbieżności z wersją angielską obowiązuje wersja angielska.'),
    ],
    acceptTip: 'Jeśli Ty (użytkownik) akceptujesz powyższą umowę, naciśnij „Akceptuję”. Jeśli nie, naciśnij „Nie akceptuję”, aby wyjść, i usuń wszystkie dane tego programu.',
  }),
}

/**
 * The licence agreement in the language of the app (English for the languages it has not been translated to)
 */
export const getPactText = (locale: string, app: PactApp): PactText => {
  const lang = getLang(locale)
  return TEXTS[lang](LICENSE_NAMES[app.license][lang], PLATFORM_NAMES[app.platform][lang])
}
