// English translations for dynamic playlist tag/category names returned by Chinese music APIs.
// Used by TagList.vue when the app locale is English.

/* eslint-disable quote-props */
const tagNameMap: Record<string, string> = {
  // Group/category headers
  '热门标签': 'Top Tags',
  '专区': 'Special',
  '主题': 'Theme',
  '心情': 'Mood',
  '情感': 'Emotion',
  '场景': 'Scene',
  '年代': 'Era',
  '曲风流派': 'Genre',
  '曲风': 'Style',
  '流派': 'Genre',
  '语言': 'Language',
  '语种': 'Language',
  '人群': 'Audience',
  '乐器': 'Instrument',
  '地区': 'Region',
  '有声系列': 'Audio Series',

  // Common tag names – genres/styles
  '全部': 'All',
  '流行': 'Pop',
  '摇滚': 'Rock',
  '民谣': 'Folk',
  '电子': 'Electronic',
  '电音': 'Electronic',
  '舞曲': 'Dance',
  '说唱': 'Rap',
  '嘻哈': 'Hip-Hop',
  'R&B': 'R&B',
  'Soul': 'Soul',
  '爵士': 'Jazz',
  '古典': 'Classical',
  '轻音乐': 'Easy Listening',
  '乡村': 'Country',
  '金属': 'Metal',
  '朋克': 'Punk',
  '蓝调': 'Blues',
  '雷鬼': 'Reggae',
  '拉丁': 'Latin',
  '世界音乐': 'World Music',
  '古风': 'Chinese Style',
  '国风': 'Chinese Style',
  '二次元': 'ACG',
  '游戏': 'Gaming',
  '影视原声': 'Soundtrack',
  '纯音乐': 'Instrumental',
  '网络歌曲': 'Internet Hits',
  '网络': 'Internet',
  '经典老歌': 'Classic Oldies',
  '新歌': 'New Releases',
  '新歌首发': 'New Releases',
  '热歌': 'Hot Songs',
  '飙升': 'Rising',
  '情歌': 'Love Songs',
  'DJ': 'DJ',
  '广场舞': 'Square Dance',
  '铃声': 'Ringtones',
  '有声书': 'Audiobooks',
  '相声': 'Crosstalk',
  '戏曲': 'Opera',
  '儿童': 'Children',
  '儿歌': 'Children\'s Songs',
  '综艺': 'Variety',
  '网红': 'Internet Famous',
  '影视': 'Film & TV',
  '动漫': 'Anime',
  'K歌': 'Karaoke',
  '小说': 'Novels',
  '佛乐': 'Buddhist Music',
  '评书': 'Storytelling',
  '短视频': 'Short Video',

  // 专区 (special-zone) compound tags
  '经典老歌专区': 'Classic Oldies',
  '网红专区': 'Internet Famous',
  'DJ专区': 'DJ',
  '轻音乐专区': 'Easy Listening',
  '国风专区': 'Chinese Style',
  '影视专区': 'Film & TV',
  '铃声专区': 'Ringtones',
  '动漫专区': 'Anime',
  '新歌首发专区': 'New Releases',
  'K歌专区': 'Karaoke',
  '小说专区': 'Novels',
  '佛乐专区': 'Buddhist Music',
  '儿童专区': 'Children',
  '评书专区': 'Storytelling',
  '综艺专区': 'Variety',
  '经典专区': 'Classic',
  '流行专区': 'Pop',
  '摇滚专区': 'Rock',
  '民谣专区': 'Folk',
  '电子专区': 'Electronic',
  '舞曲专区': 'Dance',

  // Moods
  '怀旧': 'Nostalgic',
  '清新': 'Fresh',
  '浪漫': 'Romantic',
  '伤感': 'Sad',
  '治愈': 'Healing',
  '放松': 'Relaxing',
  '孤独': 'Lonely',
  '感动': 'Moving',
  '兴奋': 'Excited',
  '快乐': 'Happy',
  '开心': 'Happy',
  '安静': 'Quiet',
  '思念': 'Missing',
  '励志': 'Inspirational',
  '甜蜜': 'Sweet',
  '难过': 'Sad',
  '慵懒': 'Laid-back',
  '愤怒': 'Angry',
  '激情': 'Passionate',
  '空灵': 'Ethereal',

  // Scenes
  '清晨': 'Morning',
  '夜晚': 'Night',
  '睡前': 'Bedtime',
  '学习': 'Study',
  '工作': 'Work',
  '运动': 'Workout',
  '开车': 'Driving',
  '旅行': 'Travel',
  '散步': 'Walking',
  '咖啡厅': 'Café',
  '酒吧': 'Bar',
  '派对': 'Party',
  '婚礼': 'Wedding',
  '逛街': 'Shopping',
  '约会': 'Date',
  '户外': 'Outdoor',
  '居家': 'Home',
  '校园': 'Campus',
  '地铁': 'Subway',
  '跑步': 'Running',

  // Eras
  '70后': '70s',
  '80后': '80s',
  '90后': '90s',
  '00后': '00s',
  '经典': 'Classic',
  '老歌': 'Oldies',
  '怀旧金曲': 'Golden Oldies',

  // Languages
  '国语': 'Mandarin',
  '普通话': 'Mandarin',
  '粤语': 'Cantonese',
  '英语': 'English',
  '日语': 'Japanese',
  '韩语': 'Korean',
  '法语': 'French',
  '德语': 'German',
  '西班牙语': 'Spanish',
  '闽南语': 'Hokkien',
  '俄语': 'Russian',
  '方言': 'Dialect',
  '小语种': 'Minority Languages',
  '欧美': 'Western',
  '中文': 'Chinese',
  '英文': 'English',
  '韩文': 'Korean',
  '日文': 'Japanese',

  // Fallback for already-English strings can be handled by returning input.
}

export const translateTagName = (name: string): string => {
  if (!name) return name
  // Only translate when the app is in English; otherwise return the original.
  // window.i18n is created in src/renderer/plugins/i18n.ts.
  if (typeof window !== 'undefined' && (window as any).i18n?.locale !== 'en-us') return name
  return tagNameMap[name] ?? name
}
